# -*- coding: utf-8 -*-
"""News Rewriting Module Notebook (LLM Engine).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13nhzE2Grs7CR_-DZUYgGBD6VUiDPZZul

#Setup and Authentication
"""

# 1. Install necessary libraries (Run this cell once)
!pip install google-genai pandas

# 2. Import libraries
import pandas as pd
import json
from google import genai
from google.genai.errors import APIError
import os
from google.colab import drive
try:
    # Use Colab's specific method for reliable secret access
    from google.colab import userdata
except ImportError:
    # Fallback for non-Colab environments
    userdata = None

print("Setup complete. Libraries imported.")

# 3. Mount Google Drive (Essential for accessing the JSON file)
drive.mount('/content/drive')
print("Google Drive mounted.")

# 4. LLM API Key and Initialization (Loads key from Colab Secrets)
GEMINI_API_KEY = None
if userdata:
    GEMINI_API_KEY = userdata.get('GEMINI_API_KEY')
else:
    GEMINI_API_KEY = os.getenv('GEMINI_API_KEY')

if not GEMINI_API_KEY:
    raise ValueError("GEMINI_API_KEY not found. Please set it in Colab Secrets (🔑).")

try:
    # Initialize the Gemini Client
    client = genai.Client(api_key=GEMINI_API_KEY)
    print("Gemini Client initialized successfully.")
except Exception as e:
    print(f"Error initializing Gemini client: {e}")

# Define the model to use for rewriting
REWRITING_MODEL = 'gemini-2.5-flash'
print(f"Using model: {REWRITING_MODEL}")

"""#Data Loading and Preparation"""

# IMPORTANT: Adjust this path if your file is in a different folder!
FILE_NAME = '/content/drive/MyDrive/NewsBot_AI/raw_articles_for_rewriting.json'

try:
    articles_df = pd.read_json(FILE_NAME, orient='records')

    # Simple cleanup: fill any potential empty body text to prevent LLM errors
    articles_df['body_text_html'] = articles_df['body_text_html'].fillna('')

    print(f"\nSuccessfully loaded {articles_df.shape[0]} articles from {FILE_NAME}")

    # Display the first article's details to confirm data integrity
    sample_article = articles_df.iloc[0]
    print(f"Sample Article Title: {sample_article['title']}")

except FileNotFoundError:
    print(f"\nERROR: File '{FILE_NAME}' not found.")
    print("ACTION: Ensure the file path is correct and Google Drive is mounted.")
    articles_df = pd.DataFrame()

"""#Persona definition"""

PERSONAS = {
    "Gen Z": {
        "age": 20,
        "tone": "Sarcastic, meme-aware, and uses Gen Z slang/emojis (e.g., 'slay,' 'bet,' 'main character,' 'vibe check').",
        "style_description": "Hyper-informal, engaging, and highly distilled to the essentials.",
        "length_target": "Keep it short, snappy, and digestible (max 150 words)."
    },
    "Professional": {
        "age": 45,
        "tone": "Serious, analytical, and uses business terminology (e.g., 'synergy,' 'KPIs,' 'optimization,' 'leveraging').",
        "style_description": "Highly professional, objective, and focused on executive summaries.",
        "length_target": "Provide a concise executive summary (max 100 words)."
    },
    "Academic": {
        "age": 30,
        "tone": "Neutral, objective, and uses complex, formal vocabulary. Must cite potential limitations or counter-arguments.",
        "style_description": "Academic, detailed, and critical analysis style.",
        "length_target": "Provide a detailed, argumentative abstract (max 250 words)."
    }
}

print("\nDefined 3 User Personas for personalized rewriting.")

"""#The News Rewriting Function (LLM Engine)"""

def rewrite_article(article: pd.Series, persona_name: str) -> dict:
    """Constructs a detailed prompt and calls the Gemini API to rewrite the article."""
    persona = PERSONAS.get(persona_name)
    if not persona:
        return {"error": f"Persona '{persona_name}' not found."}

    # 1. System Prompt (High-level instruction for the model)
    system_instruction = (
        "You are an expert content personalizer running on an AI News Platform. "
        "Your task is to rewrite the provided news article to perfectly match the target user persona's style, tone, and length. "
        "DO NOT use HTML tags. ONLY output the rewritten text."
    )

    # 2. User Prompt (The payload sent to the model)
    user_prompt = f"""
    --- REWRITING INSTRUCTIONS (PERSONA: {persona_name}) ---

    * **TARGET STYLE:** Rewrite the content in a {persona['style_description']} style.
    * **TONE:** The tone must be {persona['tone']}.
    * **LENGTH:** {persona['length_target']}
    * **AGE/DEMO:** Address a reader who is approximately {persona['age']} years old.

    --- ORIGINAL ARTICLE CONTENT ---

    Title: {article['title']}
    Original Source Topic: {article['topic']}
    Original Text:

    {article['body_text_html']}
    """

    print(f"-> Rewriting '{article['title'][:50]}...' for persona: {persona_name}...")

    try:
        # Call the Gemini API
        response = client.models.generate_content(
            model=REWRITING_MODEL,
            contents=[user_prompt],
            config=genai.types.GenerateContentConfig(
                system_instruction=system_instruction
            )
        )

        # Structure the output as a RewrittenArticle object
        return {
            "title": f"[{persona_name} Rewritten] {article['title']}",
            "content_text": response.text,
            "original_article": article['original_id'],
            "persona": persona_name
        }

    except APIError as e:
        return {
            "title": "API Error",
            "content_text": f"API ERROR: Could not rewrite article. {e}",
            "original_article": article['original_id'],
            "persona": persona_name
        }
    except Exception as e:
         return {
            "title": "Error",
            "content_text": f"An unexpected error occurred: {e}",
            "original_article": article['original_id'],
            "persona": persona_name
        }

"""#Demonstration"""

if not articles_df.empty:
    # 1. Select the first article for demonstration
    article_to_rewrite = articles_df.iloc[0]

    print(f"\n=======================================================")
    print(f"  DEMONSTRATION START")
    print(f"  Source Article: {article_to_rewrite['title']}")
    print(f"=======================================================\n")

    # 2. Rewrite the article for the Professional Persona
    professional_result = rewrite_article(article_to_rewrite, "Professional")

    # 3. Rewrite the SAME article for the Gen Z Persona
    genz_result = rewrite_article(article_to_rewrite, "Gen Z")

    # 4. Display the results clearly

    print("\n-------------------------------------------------------")
    print(f"  ORIGINAL TEXT SNIPPET (First 150 chars)")
    print("-------------------------------------------------------")
    print(f"{article_to_rewrite['body_text_html'][:150]}...\n")

    # Professional Output
    print(f"\n--- Output for Persona: {professional_result['persona']} ---")
    print(professional_result['content_text'])

    # Gen Z Output
    print(f"\n--- Output for Persona: {genz_result['persona']} ---")
    print(genz_result['content_text'])

    # 5. BONUS: Rewrite for the Academic Persona
    academic_result = rewrite_article(article_to_rewrite, "Academic")
    print(f"\n--- Output for Persona: {academic_result['persona']} ---")
    print(academic_result['content_text'])

else:
    print("\nSkipping demonstration because no articles were loaded. Check Section 2.")