# Generated by Django 5.2.7 on 2025-10-18 17:14

import articles.models
import django_mongodb_backend.fields
import django_mongodb_backend.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EmbeddedContributor",
            fields=[
                (
                    "id",
                    django_mongodb_backend.fields.ObjectIdAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contributor_id", models.CharField(max_length=255)),
                ("web_title", models.CharField(max_length=255)),
                ("web_url", models.URLField()),
                ("api_url", models.URLField()),
                ("bio", models.TextField(blank=True, null=True)),
                ("byline_image_url", models.URLField(blank=True, null=True)),
                ("byline_large_image_url", models.URLField(blank=True, null=True)),
                ("first_name", models.CharField(blank=True, max_length=100, null=True)),
                ("last_name", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "twitter_handle",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EmbeddedTag",
            fields=[
                (
                    "id",
                    django_mongodb_backend.fields.ObjectIdAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tag_id", models.CharField(max_length=100)),
                ("section_id", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "section_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("web_title", models.CharField(max_length=200)),
                ("web_url", models.URLField()),
                ("api_url", models.URLField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    django_mongodb_backend.fields.ObjectIdAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("section_id", models.CharField(max_length=100, unique=True)),
                ("web_title", models.CharField(max_length=200)),
                ("web_url", models.URLField()),
                ("api_url", models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    django_mongodb_backend.fields.ObjectIdAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("guardian_id", models.CharField(max_length=255, unique=True)),
                ("section_id", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "section_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("web_title", models.CharField(max_length=255)),
                ("web_url", models.URLField()),
                ("api_url", models.URLField()),
                ("headline", models.CharField(blank=True, max_length=255, null=True)),
                ("trail_text", models.TextField(blank=True, null=True)),
                ("body_text", models.TextField(blank=True, null=True)),
                ("thumbnail", models.URLField(blank=True, null=True)),
                ("first_publication_date", models.DateTimeField(blank=True, null=True)),
                ("last_modified", models.DateTimeField(blank=True, null=True)),
                (
                    "embedding",
                    django_mongodb_backend.fields.ArrayField(
                        base_field=models.FloatField(), blank=True, null=True, size=1024
                    ),
                ),
                (
                    "tags",
                    django_mongodb_backend.fields.EmbeddedModelArrayField(
                        blank=True,
                        default=list,
                        embedded_model=articles.models.EmbeddedTag,
                    ),
                ),
                (
                    "authors",
                    django_mongodb_backend.fields.EmbeddedModelArrayField(
                        blank=True, embedded_model=articles.models.EmbeddedContributor
                    ),
                ),
            ],
            options={
                "indexes": [
                    django_mongodb_backend.indexes.VectorSearchIndex(
                        fields=["embedding"],
                        name="text_search_index",
                        similarities=["cosine"],
                    )
                ],
            },
        ),
    ]
