# Generated by Django 5.2.7 on 2025-10-26 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0002_article_created_at_article_updated_at"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="article",
            index=models.Index(
                fields=["section_id"], name="articles_ar_section_b79354_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(
                fields=["first_publication_date"], name="articles_ar_first_p_46420e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(
                fields=["created_at"], name="articles_ar_created_b5cc75_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(
                fields=["last_modified"], name="articles_ar_last_mo_eef6c3_idx"
            ),
        ),
    ]
