# Generated by Django 5.2.7 on 2025-10-26 16:59

import django.db.models.deletion
import django_mongodb_backend.fields
import django_mongodb_backend.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0003_article_articles_ar_section_b79354_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Chunk",
            fields=[
                (
                    "id",
                    django_mongodb_backend.fields.ObjectIdAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chunk_index", models.PositiveIntegerField()),
                ("text", models.TextField()),
                (
                    "embedding",
                    django_mongodb_backend.fields.ArrayField(
                        base_field=models.FloatField(), size=1024
                    ),
                ),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="articles.article",
                    ),
                ),
            ],
            options={
                "indexes": [
                    django_mongodb_backend.indexes.VectorSearchIndex(
                        fields=["embedding"],
                        name="chunk_search_index",
                        similarities=["cosine"],
                    )
                ],
                "unique_together": {("article", "chunk_index")},
            },
        ),
    ]
