# Generated by Django 5.2.7 on 2025-10-30 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0004_chunk"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="section",
            index=models.Index(
                fields=["section_id"], name="articles_se_section_b04c3d_idx"
            ),
        ),
    ]
