# Generated by Django 5.2.7 on 2025-10-26 16:28

import django.db.models.deletion
import django_mongodb_backend.fields
import users.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("articles", "0003_article_articles_ar_section_b79354_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyHighlight",
            fields=[
                (
                    "id",
                    django_mongodb_backend.fields.ObjectIdAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("day", models.DateField(auto_now_add=True)),
                (
                    "persona_snapshot",
                    django_mongodb_backend.fields.EmbeddedModelField(
                        embedded_model=users.models.AuthorPersona
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_highlights",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Story",
            fields=[
                (
                    "id",
                    django_mongodb_backend.fields.ObjectIdAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=512)),
                ("body_text", models.TextField()),
                ("order", models.PositiveIntegerField()),
                (
                    "daily_highlight",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stories",
                        to="highlights.dailyhighlight",
                    ),
                ),
                ("source_articles", models.ManyToManyField(to="articles.article")),
            ],
            options={
                "ordering": ["order"],
                "unique_together": {("daily_highlight", "order")},
            },
        ),
    ]
