# Generated by Django 5.2.7 on 2025-10-26 16:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("highlights", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="dailyhighlight",
            index=models.Index(
                fields=["user", "-created_at"], name="highlights__user_id_07ecbe_idx"
            ),
        ),
    ]
