# Generated by Django 5.2.7 on 2025-10-30 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("highlights", "0002_dailyhighlight_highlights__user_id_07ecbe_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="story",
            name="narration",
            field=models.FileField(
                blank=True, null=True, upload_to="story_narrations/"
            ),
        ),
    ]
