# Generated by Django 5.2.7 on 2025-10-26 08:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="birthday",
            field=models.DateField(default=datetime.date(2000, 1, 1)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="gender",
            field=models.CharField(
                choices=[("m", "Male"), ("f", "Female")], default="M", max_length=1
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[("news_reader", "News Reader"), ("admin", "Admin")],
                default="news_reader",
                max_length=11,
            ),
            preserve_default=False,
        ),
    ]
