# Generated by Django 5.2.7 on 2025-10-26 10:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_bookmark"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookmark",
            name="user",
            field=models.ForeignKey(
                limit_choices_to={"user_type": "news_reader"},
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
