# Generated by Django 5.2.7 on 2025-10-26 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_bookmark_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="birthday",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("m", "Male"), ("f", "Female")],
                max_length=1,
                null=True,
            ),
        ),
    ]
