# Generated by Django 5.2.7 on 2025-11-06 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0001_initial"),
        ("users", "0005_alter_user_birthday_alter_user_gender"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={},
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["user_type"], name="users_user_user_ty_4573bb_idx"
            ),
        ),
    ]
